version: '3'
services:
  longhorn:
    image: okapiframework/okapi-longhorn:latest
    restart: unless-stopped
    volumes:
     - ./docker/Okapi-Longhorn-Files:/home/jetty/Okapi-Longhorn-Files
    expose:
     - "8080"
  js-client:
    build: .
    volumes:
     - ./:/usr/src/app
  nginx:
    image: nginx:stable-alpine
    links:
      - longhorn:longhorn
      - js-client:js-client
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"